{
 "title": "SR Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(starrocks_be_compaction_bytes_total{job=\"starrocks_exporter\"},instance)"
    }
   },
   { "name": "interval", "query": "1m,2m,5m,10m,1h" },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(starrocks_be_compaction_bytes_total{job=\"starrocks_exporter\", instance=~\"$instance\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "starrocks_fe_txn_running",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by(db) (starrocks_fe_txn_running{env=\"Production\", service=\"DWH-StarRocks\"})",
       "legendFormat": "{{db}}"
      }
     ]
    },
    {
     "title": "starrocks_fe_txn",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(starrocks_fe_txn_begin{env=\"Production\", service=\"DWH-StarRocks\"}[$interval])",
       "legendFormat": "begin - {{instance}}"
      },
      {
       "expr": "rate(starrocks_fe_txn_failed{env=\"Production\", service=\"DWH-StarRocks\"}[$interval])",
       "legendFormat": "failed - {{instance}}"
      },
      {
       "expr": "rate(starrocks_fe_txn_reject{env=\"Production\", service=\"DWH-StarRocks\"}[$interval])",
       "legendFormat": "reject - {{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_fe_txn_failed ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(starrocks_fe_txn_failed{env=\"Production\", service=\"DWH-StarRocks\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_txn_request exec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_txn_request{env=\"Production\", service=\"DWH-StarRocks\", type=\"exec\"}[$interval])",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "starrocks_be_txn_request commit",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_txn_request{env=\"Production\", service=\"DWH-StarRocks\", type=\"commit\"}[$interval])",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "starrocks_be_txn_request rollback",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_txn_request{env=\"Production\", service=\"DWH-StarRocks\", type=\"rollback\"}[$interval])",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "starrocks_be_create_tablet_running_threads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "starrocks_be_create_tablet_running_threads{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_create_tablet_queue_count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "targets": [
      {
       "expr": "starrocks_be_create_tablet_queue_count{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_create_tablet_execute_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_create_tablet_execute_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total starrocks_be_engine_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "rate(starrocks_be_engine_requests_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\", status=\"total\"}[$interval])",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "starrocks_be_create_tablet_pending_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_create_tablet_pending_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_create_tablet_pending_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_create_tablet_pending_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_create_tablet_executed_tasks_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_create_tablet_executed_tasks_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_async_delta_writer_execute_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_async_delta_writer_execute_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_async_delta_writer_pending_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_async_delta_writer_pending_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_pipe_driver_execution_time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_pipe_driver_execution_time{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_update_rowset_commit_request_failed ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_update_rowset_commit_request_failed{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_update_apply_execute_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_update_apply_execute_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_compact_pool_execute_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_compact_pool_execute_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process_faults_major",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "rate(process_faults_minor_second{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_segment_replicate_execute_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_segment_replicate_execute_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_query_scan_bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_query_scan_bytes{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[1h])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed starrocks_be_engine_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 67 },
     "targets": [
      {
       "expr": "rate(starrocks_be_engine_requests_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "process_faults_minor_second",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_compact_pool_pending_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_update_apply_pending_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_update_apply_pending_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_load+channel_coumt",
     "type": "timeseries",
     "description": "количество активных каналов загрузки",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 73 },
     "targets": [
      {
       "expr": "rate(starrocks_be_load_channel_count{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])"
      }
     ]
    },
    {
     "title": "starrocks_be_check_consistency_pending_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_check_consistency_pending_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_check_consistency_executed_tasks_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "rate(starrocks_be_check_consistency_executed_tasks_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "starrocks_be_check_consistency_threadpool_size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 79 },
     "targets": [
      {
       "expr": "starrocks_be_check_consistency_threadpool_size{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - size"
      },
      {
       "expr": "starrocks_be_check_consistency_running_threads{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - running"
      }
     ]
    },
    {
     "title": "starrocks_be_check_consistency_execute_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_check_consistency_execute_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "starrocks_be_check_consistency_queue_count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "rate(starrocks_be_check_consistency_queue_count{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} - {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MemtableFlush ThreadPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "memtable_flush_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(starrocks_be_memtable_flush_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memtable_flush_pending_time_per_task",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_memtable_flush_pending_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval]) / rate(starrocks_be_memtable_flush_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memtable_flush_disk_throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_memtable_flush_disk_bytes_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memtable_flush_executed_tasks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(starrocks_be_memtable_flush_executed_tasks_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memtable_flush_duration_per_task",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_memtable_flush_duration_us{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval]) / rate(starrocks_be_memtable_flush_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memtable_flush_memory_throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_memtable_flush_memory_bytes_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memtable_flush_threadpool_threads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "starrocks_be_memtable_flush_active_threads{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "active_{{instance}}"
      },
      {
       "expr": "starrocks_be_memtable_flush_running_threads{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "running_{{instance}}"
      },
      {
       "expr": "starrocks_be_memtable_flush_threadpool_size{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "size_{{instance}}"
      }
     ]
    },
    {
     "title": "memtable_flush_execute_time_per_task",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_memtable_flush_execute_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval]) / rate(starrocks_be_memtable_flush_executed_tasks_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memtable_flush_iotime_per_task",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_memtable_flush_io_time_us{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$__rate_interval]) / rate(starrocks_be_memtable_flush_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memtable_flush_queue_count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "starrocks_be_memtable_flush_queue_count{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memtable_flush_finalize_duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_memtable_finalize_duration_us{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SegmentFlush ThreadPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "segment_flush_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(starrocks_be_segment_flush_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "segment_flush_pending_time_per_task",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_segment_flush_pending_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval]) / rate(starrocks_be_segment_flush_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "segment_flush_duration_per_task",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_segment_flush_duration_us{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval]) / rate(starrocks_be_segment_flush_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "segment_flush_executed_tasks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(starrocks_be_segment_flush_executed_tasks_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "segment_flush_io_time_per_task",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_segment_flush_io_time_us{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval]) / rate(starrocks_be_segment_flush_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "segment_flush_queue_count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "starrocks_be_segment_flush_queue_count{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "segment_flush_threadpool_threads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "starrocks_be_segment_flush_active_threads{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "active_{{instance}}"
      },
      {
       "expr": "starrocks_be_segment_flush_running_threads{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "running_{{instance}}"
      },
      {
       "expr": "starrocks_be_segment_flush_threadpool_size{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}",
       "legendFormat": "size_{{instance}}"
      }
     ]
    },
    {
     "title": "segment_flush_execute_time_per_task",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_segment_flush_execute_time_ns_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval]) / rate(starrocks_be_segment_flush_executed_tasks_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDb Meta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "rocksdb_meta_read_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_meta_request_duration{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\", type=\"read\"}[$__rate_interval]) / rate(starrocks_be_meta_request_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\", type=\"read\"}[$__rate_interval])",
       "legendFormat": "{{instance}}_{{type}}"
      }
     ]
    },
    {
     "title": "rocksdb_meta_write_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_meta_request_duration{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\", type=\"write\"}[$__rate_interval]) / rate(starrocks_be_meta_request_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\", type=\"write\"}[$__rate_interval])",
       "legendFormat": "{{instance}}_{{type}}"
      }
     ]
    },
    {
     "title": "rocksdb_meta_write_ops",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_meta_request_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\", type=\"write\"}[$__rate_interval])",
       "legendFormat": "{{instance}}_{{type}}"
      }
     ]
    },
    {
     "title": "rocksdb_meta_read_ops",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_meta_request_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$instance\", type=\"read\"}[$__rate_interval])",
       "legendFormat": "{{instance}}_{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend Thrift-server-pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "pool_size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "starrocks_fe_thread_pool{env=\"Production\", name=\"thrift-server-pool\", type=\"pool_size\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "completed_task_count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(starrocks_fe_thread_pool{env=\"Production\", name=\"thrift-server-pool\", type=\"completed_task_count\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "task_in_queue",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "starrocks_fe_thread_pool{env=\"Production\", name=\"thrift-server-pool\", type=\"task_in_queue\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "active_thread_num",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "starrocks_fe_thread_pool{env=\"Production\", name=\"thrift-server-pool\", type=\"active_thread_num\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Bthread", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "bthread worker load",
   "type": "timeseries",
   "description": "bthread_worker_usage / bthread_worker_count, represent the heavy usage of pthreads executing bthread tasks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bthread_worker_usage{instance =~ \"$instance\"} / bthread_worker_count{instance =~ \"$instance\"}"
    }
   ]
  },
  {
   "title": "BRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC:write_add_chunks qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rpc_server_8060_starrocks_pinternal_service_tablet_writer_add_chunks_qps{instance =~ \"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RPC:write_add_chunks concurrency",
     "type": "timeseries",
     "description": "{instance =~ \"$instance\"}",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rpc_server_8060_starrocks_pinternal_service_tablet_writer_add_chunks_concurrency{instance =~ \"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "pending_load_task_scheduler_pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "pool_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "starrocks_fe_thread_pool{env=\"Production\",name=\"pending_load_task_scheduler_pool\",type=\"pool_size\"}"
      }
     ]
    },
    {
     "title": "task_in_queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "starrocks_fe_thread_pool{env=\"Production\",name=\"pending_load_task_scheduler_pool\",type=\"task_in_queue\"}"
      }
     ]
    },
    {
     "title": "active_thread_num",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "starrocks_fe_thread_pool{env=\"Production\",name=\"pending_load_task_scheduler_pool\",type=\"active_thread_num\"}"
      }
     ]
    },
    {
     "title": "completed_task_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "starrocks_fe_thread_pool{env=\"Production\",name=\"pending_load_task_scheduler_pool\",type=\"completed_task_count\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Async RPC Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Async Load Pool Active/Total Thread Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "starrocks_be_load_channel_active_threads{env=\"Production\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}_active"
      },
      {
       "expr": "starrocks_be_load_channel_threadpool_size{env=\"Production\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}_size"
      },
      {
       "expr": "starrocks_be_load_channel_running_threads{env=\"Production\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}_running"
      }
     ]
    },
    {
     "title": "load channel addChunkDuration Per Task",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_load_channel_add_chunks_duration_us{env=\"Production\", instance=~\"$instance\"}[$__rate_interval]) / rate(starrocks_be_load_channel_add_chunks_total{env=\"Production\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "load channel execute time per task",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_load_channel_execute_time_ns_total{env=\"Production\", instance=~\"$instance\"}[$__rate_interval]) / rate(starrocks_be_load_channel_executed_tasks_total{env=\"Production\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "load channel duration break down per task",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_load_channel_add_chunks_wait_memtable_duration_us{env=\"Production\", instance=~\"$instance\"}[$__rate_interval]) / rate(starrocks_be_load_channel_add_chunks_total{env=\"Production\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}_memtable"
      },
      {
       "expr": "rate(starrocks_be_load_channel_add_chunks_wait_replica_duration_us{env=\"Production\", instance=~\"$instance\"}[$__rate_interval]) / rate(starrocks_be_load_channel_add_chunks_total{env=\"Production\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}_replica"
      },
      {
       "expr": "rate(starrocks_be_load_channel_add_chunks_wait_writer_duration_us{env=\"Production\", instance=~\"$instance\"}[$__rate_interval]) / rate(starrocks_be_load_channel_add_chunks_total{env=\"Production\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}_writer"
      }
     ]
    },
    {
     "title": "load channel pending time per task",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(starrocks_be_load_channel_pending_time_ns_total{env=\"Production\", instance=~\"$instance\"}[$__rate_interval]) / rate(starrocks_be_load_channel_executed_tasks_total{env=\"Production\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Clone Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Clone Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(starrocks_be_clone_task_copy_bytes{env=\"Production\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}__{{type}}"
    }
   ]
  },
  {
   "title": "Clone Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "increase(starrocks_be_engine_requests_total{env=\"Production\", instance=~\"$instance\", type=\"clone\", status=\"total\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clone Requests Fails Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "increase(starrocks_be_engine_requests_total{env=\"Production\", instance=~\"$instance\", type=\"clone\", status=\"failed\"}[1m])",
     "legendFormat": "{{instance}}_{{status}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes Standard Deviation (Hourly)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(increase(node_disk_written_bytes_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$node:9100\"}[1h]) - scalar(avg(increase(node_disk_written_bytes_total{env=\"Production\", service=\"DWH-StarRocks\"}[1h])))) / scalar( stddev(increase(node_disk_written_bytes_total{env=\"Production\", service=\"DWH-StarRocks\"}[1h]))) > 2",
     "legendFormat": "{{instance}}_{{device}}_abnormal"
    }
   ]
  },
  {
   "title": "number of Counts Disk Write Bytes > 3 * Standard Deviation ",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(increase(node_disk_written_bytes_total{env=\"Production\", service=\"DWH-StarRocks\", instance=~\"$node:9100\"}[1h]) - scalar(avg(increase(node_disk_written_bytes_total{env=\"Production\", service=\"DWH-StarRocks\"}[1h])))) / scalar( stddev(increase(node_disk_written_bytes_total{env=\"Production\", service=\"DWH-StarRocks\"}[1h]))) > 3",
     "legendFormat": "{{instance}}_{{device}}_abnormal"
    }
   ]
  },
  {
   "title": "Number of tablets in error state in the cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  -- 将 DATETIME 转换为 UNIX 时间戳，Grafana 会自动根据时区配置显示正确时间\r\n  UNIX_TIMESTAMP(t.update_time) AS time, \r\n  SUM(t.error_cnt) AS errstatnum\r\nFROM (\r\n  SELECT\r\n    update_time,\r\n    json_length(parse_json(errorStateTablets)) AS error_cnt\r\n  FROM\r\n    dbms.monitor_db_tablet_stat\r\n) t\r\nGROUP BY t.update_time\r\nORDER BY time;"
    }
   ]
  }
 ]
}