{
 "title": "StarRocks Query Resource & Performance Analysis",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": "SELECT DISTINCT user FROM starrocks_audit_db__.starrocks_audit_tbl__  where timestamp >= date(now())- interval 1 day ORDER BY user;"
   },
   {
    "name": "digest",
    "label": "Digest",
    "query": "SELECT DISTINCT digest FROM starrocks_audit_db__.starrocks_audit_tbl__  where timestamp >= date(now())- interval 1 day ORDER BY digest;"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster CPU & Memory Usage (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT str_to_date(minute, '%Y-%m-%d %H:%i'), SUM(cpu_seconds) AS cpu_total, SUM(mem_mb) AS mem_total FROM starrocks_audit_db__.mv_audit_minute_agg WHERE $__timeFilter(minute) GROUP BY str_to_date(minute, '%Y-%m-%d %H:%i') ORDER BY str_to_date(minute, '%Y-%m-%d %H:%i');"
    }
   ]
  },
  {
   "title": "Top Users by CPU (within selected time)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT user, SUM(cpu_seconds) AS cpu_total FROM starrocks_audit_db__.mv_audit_minute_agg WHERE $__timeFilter(minute) GROUP BY user ORDER BY cpu_total DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Top Users by Memory",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT user, SUM(mem_mb) AS mem_total FROM starrocks_audit_db__.mv_audit_minute_agg WHERE $__timeFilter(minute) GROUP BY user ORDER BY mem_total DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Top Users by Scanbytes",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT user, SUM(scan_mb) AS scan_total_mb FROM starrocks_audit_db__.mv_audit_minute_agg WHERE $__timeFilter(minute) GROUP BY user ORDER BY scan_total_mb DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Top Users by Scanrows",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT user, SUM(scan_rows) AS scan_rows_total FROM starrocks_audit_db__.mv_audit_minute_agg WHERE $__timeFilter(minute) GROUP BY user ORDER BY scan_rows_total DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Top Users by Scanrows, return_rows_total",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT user, SUM(return_rows) AS return_rows_total FROM starrocks_audit_db__.mv_audit_minute_agg WHERE $__timeFilter(minute) GROUP BY user ORDER BY return_rows_total DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Top SQL Digests by CPU/Memory",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT minute, digest, SUM(cpu_seconds) AS cpu_total, SUM(mem_mb) AS mem_total, SUM(scan_mb) AS scan_total, SUM(query_count) AS queries FROM starrocks_audit_db__.mv_audit_minute_agg WHERE $__timeFilter(minute) GROUP BY minute,digest ORDER BY cpu_total DESC LIMIT 15;"
    }
   ]
  },
  {
   "title": "User CPU Usage Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "targets": [
    {
     "rawSql": "SELECT str_to_date(minute, '%Y-%m-%d %H'), SUM(cpu_seconds) AS cpu_total FROM starrocks_audit_db__.mv_audit_minute_agg  where $__timeFilter(minute) and user='$user' GROUP BY str_to_date(minute, '%Y-%m-%d %H') ORDER BY str_to_date(minute, '%Y-%m-%d %H');"
    }
   ]
  },
  {
   "title": "User Memory Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
   "targets": [
    {
     "rawSql": "SELECT str_to_date(minute, '%Y-%m-%d %H'), SUM(mem_mb) AS mem_total FROM starrocks_audit_db__.mv_audit_minute_agg where $__timeFilter(minute)  and user='$user' GROUP BY str_to_date(minute, '%Y-%m-%d %H') ORDER BY str_to_date(minute, '%Y-%m-%d %H');"
    }
   ]
  },
  {
   "title": "Digest CPU Trend ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
   "targets": [
    {
     "rawSql": "SELECT str_to_date(minute, '%Y-%m-%d %H'), SUM(cpu_seconds) AS cpu_total FROM starrocks_audit_db__.mv_audit_minute_agg WHERE $__timeFilter(minute) and digest='$digest' GROUP BY str_to_date(minute, '%Y-%m-%d %H') ORDER BY str_to_date(minute, '%Y-%m-%d %H');"
    }
   ]
  },
  {
   "title": "Slow Query Count (queryTime > 10s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT str_to_date(timestamp, '%Y-%m-%d %H:%i:00') AS minute, COUNT(*) AS slow_queries FROM starrocks_audit_db__.starrocks_audit_tbl__ WHERE timestamp>=date(now()) -interval 1 day AND queryTime > 10000 GROUP BY minute ORDER BY minute;"
    }
   ]
  },
  {
   "title": "Query Details (Drilldown by Digest)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, user, queryId, cpuCostNs/1e9 AS cpu_seconds, memCostBytes/1024/1024 AS mem_mb, scanBytes/1024/1024 AS scan_mb, scanrows AS scan_rows, returnrows AS return_rows, queryTime/1000 AS query_time_s, SUBSTRING(stmt,1,300) AS stmt_preview FROM  starrocks_audit_db__.starrocks_audit_tbl__\r\nWHERE $__timeFilter(timestamp) AND digest = '$digest' ORDER BY timestamp DESC LIMIT 500;"
    }
   ]
  },
  {
   "title": "Query Details (Drilldown by User)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, user, queryId, cpuCostNs/1e9 AS cpu_seconds, memCostBytes/1024/1024 AS mem_mb, scanBytes/1024/1024 AS scan_mb, scanrows AS scan_rows, returnrows AS return_rows, queryTime/1000 AS query_time_s, SUBSTRING(stmt,1,300) AS stmt_preview FROM  starrocks_audit_db__.starrocks_audit_tbl__\r\nWHERE $__timeFilter(timestamp) AND user='$user' ORDER BY timestamp DESC LIMIT 500;"
    }
   ]
  }
 ]
}